#include "log_manager.h"
#include <fstream>
#include <sstream>
#include <iostream>
#include <cstring>
#include <chrono>
#include <random>
#include <iomanip>

namespace cmse::utils {

    /**
     * generateSyntheticLogs
     * Uses C++11 random engines to simulate a multi-host, multi-service environment.
     */
    std::vector<LogRecord> LogManager::generateSyntheticLogs(int count, int64_t start_id, int time_range_ms) {
        std::vector<LogRecord> logs;
        logs.reserve(count); // Optimize by pre-allocating the vector capacity

        // Initialize high-quality random number generation
        std::random_device rd;
        std::mt19937 gen(rd());

        // Define distributions for various fields to simulate real-world variance
        std::uniform_int_distribution<> prio_dist(0, 7);       // Syslog priority levels
        std::uniform_int_distribution<> pid_dist(100, 9999);   // Typical Unix PIDs
        std::uniform_int_distribution<long long> time_dist(0, time_range_ms); // Random offsets

        // Static pools for categorical data
        const char* sources[] = { "systemd", "kernel", "sshd", "nginx", "mysql" };
        const char* hosts[] = { "web-01", "db-01", "lb-01", "backup-01" };

        // Use the current wall-clock time as the baseline for the log set
        auto base_time = std::chrono::system_clock::now();

        for (int i = 0; i < count; ++i) {
            LogRecord record;

            // 1. TIMESTAMP CALCULATION
            // Calculate a random offset and convert the time point to 64-bit microseconds (POSIX)
            long long offset_ms = time_dist(gen);
            auto timestamp_tp = base_time + std::chrono::milliseconds(offset_ms);
            record.timestamp = std::chrono::duration_cast<std::chrono::microseconds>(
                timestamp_tp.time_since_epoch()).count();

            // 2. PRIORITY & 3. PID
            record.priority = prio_dist(gen);
            record.pid = pid_dist(gen);

            // 4. SOURCE & HOST SELECTION (Cyclic distribution for balance)
            int src_idx = i % 5;
            int host_idx = i % 4;

            // Use buffer-safe copy logic to populate fixed-size character arrays
            strncpy_s(record.source, sizeof(record.source), sources[src_idx], _TRUNCATE);
            strncpy_s(record.host, sizeof(record.host), hosts[host_idx], _TRUNCATE);

            // 5. MESSAGE GENERATION
            // Create a payload that identifies its sequence number for verification
            std::string msg = "Synthetic log message number " + std::to_string(i);
            strncpy_s(record.message, sizeof(record.message), msg.c_str(), _TRUNCATE);

            logs.push_back(record);
        }

        return logs;
    }

    /**
     * writeLogsToFile
     * Writes the logs in a human-readable pipe-delimited format.
     */
    void LogManager::writeLogsToFile(const std::vector<LogRecord>& logs, const std::string& filename) {
        std::ofstream outfile(filename);
        if (!outfile.is_open()) {
            std::cerr << "[LogManager] Error: Could not open file " << filename << std::endl;
            return;
        }

        for (const auto& log : logs) {
            // Leverage the LogRecord's internal string conversion
            outfile << log.toString() << "\n";
        }
        outfile.close();
    }

    /**
     * readLogsFromFile
     * A basic backward-compatibility reader.
     */
    std::vector<LogRecord> LogManager::readLogsFromFile(const std::string& filename) {
        std::vector<LogRecord> logs;
        std::ifstream infile(filename);
        std::string line;

        // Iterate through lines, skipping any empty whitespace
        while (std::getline(infile, line)) {
            if (!line.empty()) {
                logs.push_back(parseLine(line));
            }
        }
        return logs;
    }

    /**
     * parseLine
     * A "rough" parser specifically for the format generated by toString().
     * Example format: "TS:1738853609000 | PRI:3 | PID:1234 | ..."
     */
    LogRecord LogManager::parseLine(const std::string& line) {
        LogRecord record = {}; // Initialize with zeros to avoid garbage values

        try {
            // Find the "TS:" marker and extract the numeric timestamp
            size_t ts_pos = line.find("TS:");
            if (ts_pos != std::string::npos) {
                // substr starts 3 chars after "TS:" and ends at the next pipe delimiter
                record.timestamp = std::stoll(line.substr(ts_pos + 3, line.find(" |", ts_pos)));
            }
            // Note: Other fields (PID, Priority, etc.) could be parsed similarly if needed.
        }
        catch (...) {
            // On error, reset to 0 to signal a corrupted/invalid record
            record.timestamp = 0;
        }
        return record;
    }

} // namespace cmse::utils